# Collector specific configuration
dataset_name: "venezuela-who-does-what-and-where-3w"

base_url: "https://rolac345w.humanitarianresponse.info/es/api/v2/dataset-api"

dataset_number:
  2024: 87

hxltags:
  "id": "#meta+id"
  "report_month": "#date+reported"
  "org_leader": "#org+leader+name"
  "org_leader_type": "#org+leader+type"
  "org_implementer": "#org+impl+name"
  "org_implementer_ve": "#org+impl+ve"
  "org_implementer_type": "#org+impl+type"
  "sector": "#sector"
  "activity_code": "#activity+code"
  "activity_name": "#activity+name"
  "activity_detail": "#activity+detail"
  "project_code": "#activity+project+code"
  "project_name": "#activity+project+name"
  "adm1_pcode": "#adm1+code"
  "adm1_name": "#adm1+name"
  "adm2_pcode": "#adm2+code"
  "adm2_name": "#adm2+name"
  "adm3_pcode": "#adm3+code"
  "adm3_name": "#adm3+name"
  "adm4_pcode": "#adm4+code"
  "adm4_name": "#adm4+name"
  "tlocation": "#loc+type"
  "location_name": "#location+name"
  "location_detail": "#loc+detail"
  "reached": "#reached"
